# Generated by Django 4.2.1 on 2023-05-11 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pixme_social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='pixme_social.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='pixme_social.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
