# Generated by Django 4.2.1 on 2023-05-11 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pixme_social', '0002_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='is_following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='pixme_social.profile'),
        ),
    ]
