# Generated by Django 4.2.1 on 2023-05-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixme_social', '0003_alter_follow_is_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
