# Generated by Django 4.2.1 on 2023-05-11 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixme_social', '0004_follow_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='user',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='is_following',
            new_name='profile',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('profile', 'follower')},
        ),
        migrations.RemoveField(
            model_name='follow',
            name='number',
        ),
    ]
