# Generated by Django 4.2.1 on 2023-05-12 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixme_social', '0008_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='CommentModel',
        ),
    ]
