# Generated by Django 4.2.1 on 2023-05-12 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixme_social', '0009_rename_comment_commentmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentModel',
            new_name='Comment',
        ),
    ]
